# Dockerfile for Python based RDKit implementation
# Based on Debian.

FROM debian:buster

RUN apt-get update &&\
 #apt-get upgrade -y &&\ 
 apt-get install -y --no-install-recommends\
 python\
 python-dev\
 python-numpy\
 python-pip\
 python-setuptools\
 python-wheel\
 python-six\
 gcc\
 libboost-system1.67.0\
 libboost-thread1.67.0\
 libboost-serialization1.67.0\
 libboost-python1.67.0\
 libboost-regex1.67.0\
 libboost-chrono1.67.0\
 libboost-date-time1.67.0\
 libboost-atomic1.67.0\
 sqlite3\
 wget\
 netcat\
 libcairo2-dev\
 libjpeg-dev\
 libgif-dev\
 zip &&\
 apt-get clean -y

ARG DOCKER_TAG=latest

COPY artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Runtime.deb artifacts/debian/$DOCKER_TAG/debs/RDKit-*-Linux-Python.deb /tmp/
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb

# set working directory
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

ENV FLASK_APP /usr/src/app/manage.py

# run server
CMD ["/usr/src/app/entrypoint.sh"]
